#!/usr/bin/env python3
"""Render the TypeScript projection of the Focus Web wire catalog."""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bot.focus_web_wire_catalog import (  # noqa: E402
    FOCUS_WEB_ENDPOINTS,
    FOCUS_WEB_ENUMS,
    FOCUS_WEB_EVENTS,
    FOCUS_WEB_RECORDS,
    FOCUS_WEB_RUNTIME_NOTICE_FIELD_LIMIT_BYTES,
    FOCUS_WEB_WIRE_VERSION,
)


OUTPUT_PATH = REPO_ROOT / "web" / "src" / "focus" / "focusWire.generated.ts"


def _json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, separators=(",", ": "))


def render_typescript() -> str:
    endpoints = {
        endpoint.name: {
            "method": endpoint.method,
            "path": endpoint.path,
            "pathParameters": list(endpoint.path_parameters),
        }
        for endpoint in FOCUS_WEB_ENDPOINTS
    }
    events = [event.name for event in FOCUS_WEB_EVENTS]
    thread_events = [event.name for event in FOCUS_WEB_EVENTS if event.thread_scoped]
    enums = {enum.name: list(enum.values) for enum in FOCUS_WEB_ENUMS}
    records = {
        record.name: {
            "typescriptType": record.typescript_type,
            "requiredFields": list(record.required_fields),
            "enumFields": dict(record.enum_fields),
        }
        for record in FOCUS_WEB_RECORDS
    }
    return f"""// Generated by scripts/generate_focus_web_wire.py. DO NOT EDIT.

export const FOCUS_WEB_WIRE_VERSION = {FOCUS_WEB_WIRE_VERSION} as const;
export const FOCUS_WEB_RUNTIME_NOTICE_FIELD_LIMIT_BYTES = {FOCUS_WEB_RUNTIME_NOTICE_FIELD_LIMIT_BYTES} as const;

export const FOCUS_WEB_ENDPOINTS = {_json(endpoints)} as const;

export type FocusWebEndpointName = keyof typeof FOCUS_WEB_ENDPOINTS;
export type FocusWebEndpointMethod =
  (typeof FOCUS_WEB_ENDPOINTS)[FocusWebEndpointName]['method'];

export function focusWebEndpointPath(
  name: FocusWebEndpointName,
  parameters: Readonly<Record<string, string>> = {{}},
): string {{
  const endpoint = FOCUS_WEB_ENDPOINTS[name];
  const expected = new Set<string>(endpoint.pathParameters);
  for (const key of Object.keys(parameters)) {{
    if (!expected.has(key)) throw new Error(`Unexpected ${{name}} path parameter: ${{key}}`);
  }}
  return endpoint.path.replace(/[{{]([a-z][a-z0-9_]*)[}}]/g, (_match, key: string) => {{
    const value = parameters[key];
    if (!value) throw new Error(`Missing ${{name}} path parameter: ${{key}}`);
    return encodeURIComponent(value);
  }});
}}

export const FOCUS_WEB_ENUMS = {_json(enums)} as const;
export type FocusWebWireEnumName = keyof typeof FOCUS_WEB_ENUMS;
export type FocusWebWireEnum<Name extends FocusWebWireEnumName> =
  (typeof FOCUS_WEB_ENUMS)[Name][number];

export function isFocusWebWireEnum<Name extends FocusWebWireEnumName>(
  name: Name,
  value: unknown,
): value is FocusWebWireEnum<Name> {{
  return typeof value === 'string'
    && (FOCUS_WEB_ENUMS[name] as readonly string[]).includes(value);
}}

export const FOCUS_WEB_RECORDS = {_json(records)} as const;
export type FocusWebWireRecordName = keyof typeof FOCUS_WEB_RECORDS;

export function hasFocusWebRequiredFields(
  name: FocusWebWireRecordName,
  value: Readonly<Record<string, unknown>>,
): boolean {{
  return FOCUS_WEB_RECORDS[name].requiredFields.every(
    (field) => Object.prototype.hasOwnProperty.call(value, field),
  );
}}

export const FOCUS_WEB_EVENT_TYPES = {_json(events)} as const;
export type FocusWebEventType = (typeof FOCUS_WEB_EVENT_TYPES)[number];
export const FOCUS_WEB_EVENT_TYPE_SET: ReadonlySet<string> =
  new Set<string>(FOCUS_WEB_EVENT_TYPES);

export function isFocusWebEventType(value: unknown): value is FocusWebEventType {{
  return typeof value === 'string' && FOCUS_WEB_EVENT_TYPE_SET.has(value);
}}

export const FOCUS_WEB_THREAD_SCOPED_EVENT_TYPES = {_json(thread_events)} as const;
export const FOCUS_WEB_THREAD_SCOPED_EVENT_TYPE_SET: ReadonlySet<string> =
  new Set<string>(FOCUS_WEB_THREAD_SCOPED_EVENT_TYPES);
"""


def check_output() -> bool:
    expected = render_typescript()
    actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if actual == expected:
        return True
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(OUTPUT_PATH),
        tofile="generated",
        lineterm="",
    )
    print("\n".join(diff))
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return 0 if check_output() else 1
    OUTPUT_PATH.write_text(render_typescript(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
